services:
  nats:
    image: 'nats:0.8.0'
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
    ports:
      - "4222:4222"
    hostname: nats-server
  mongodb:
      container_name: mongodb
      ports:
          - 27017:27017
      image: mongodb/mongodb-community-server:latest