services:
  nats:
    image: 'nats:0.8.0'
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
    ports:
      - "4222:4222"
    hostname: nats-server
  pgdb:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: "pgdbpassword"
      POSTGRES_DB: key_manager_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 30
    container_name: pgdb